### ISSUE TITLE
No Docker Image

### ISSUE THREAD

**Issue by TheBros35** [Enriquito/youtube-dl-front#2]
There is no docker image built for this. I will work off of the current codebase and try to create one. If I haven't posted back in a few days consider that I failed :)

**Comment by csloz** [comment]
Was about to add this - dockerise!

I second this!

**Comment by csloz** [comment]
**What I have so far**

#make a folder for the docker bits
mkdir youtube-dl-front
cd youtube-dl-front

#pull a nice premade make script
wget  https://raw.githubusercontent.com/mvanholsteijn/docker-makefile/master/Makefile  
wget  https://raw.githubusercontent.com/mvanholsteijn/docker-makefile/master/.make-release-support

```
#make our Dockerfile
echo <<EOF  > Dockerfile
FROM alpine
WORKDIR /

#copy run script
COPY run.sh /run.sh

#install dependencies
ENV APK_ADD="nodejs npm git bash youtube-dl ffmpeg"
RUN apk add --no-cache ${APK_ADD}
RUN git clone https://github.com/Enriquito/youtube-dl-front
WORKDIR /youtube-dl-front/server
RUN touch database.json
RUN npm install

#setup ports and volumes (volume tbd), startup script
EXPOSE 3000
VOLUME ["/youtube-dl-front/server/videos"]
ENTRYPOINT [ "/run.sh" ]
EOF
```

#Make our run.sh script
```
echo <<EOF  > run.sh
#!/bin/bash
cd /youtube-dl-front/server
node app.js
EOF
```


#now run make
make

It should build the container.  


Sample docker-compose.yml

```
   youtube-dl-front:
    image: root/ydf
    container_name: ydf
    ports:
      - 3000:3000
    volumes:
      - /opt/youtube-dl-front/videos:/youtube-dl-front/server/videos
      - /opt/youtube-dl-front/music:/youtube-dl-front/server/music
#      - /opt/youtube-dl-front/database.json:/youtube-dl-front/server/database.json
    labels:
      - "traefik.http.routers.ydf.rule=Host(`ydf.wayfarer.computersolutions.cn`,`ydf.wayfarer.yoonix.co.za`)"
      - "traefik.http.routers.ydf.middlewares=test-auth@docker"
    networks:
      - public
```
  

NOTE - database.json isn't being backed up on local FS, downloaded videos, and music are.
Still working out how to map database.json locally in a nice way.

I use traefik..  you'll need to update YOURDOMAIN to something usable for you if you also haz traefik.

**I'm STILL TESTING, will update once done!**

**Comment by Enriquito** [comment]
Thanks for looking into this! I dont have that many experiance with docker. I will test it out soon.

**Comment by csloz** [comment]
Not having fun(tm) yet - 

cd /youtube-dl-front/server
node app.js 

Is failing with - 

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/youtube-dl-front/server/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Enriquito** [comment]
Did you install all the npm modules? like this? Then you can copy the node_modules folder.

`cd /youtube-dl-front/server` 
`npm install`

**Comment by csloz** [comment]
Ok, seems to work, although I need to ideally map database.json
alternately if you can stick config files into a separate folder, and I can map that at runtime?

I'm assuming you'll make the docker files in your account, the above is enough to get started.  you'll need to setup an account on docker.io then publish.

This is the script i used - has some instructions.
https://binx.io/blog/2017/10/07/makefile-for-docker-images/

Let me know if this makes sense or not.

**Comment by csloz** [comment]
For now, I'm manually creating a database.json file in my /opt/youtube-dl-front/database.json
with this content

database.json
`{"videos":[]}`


and mapping to /youtube-dl-front/server/database.json

With:

```
  youtube-dl-front:
    image: root/ydf
    container_name: ydf
    ports:
      - 3000:3000
    volumes:
      - /opt/youtube-dl-front/videos:/youtube-dl-front/server/videos
      - /opt/youtube-dl-front/music:/youtube-dl-front/server/music
      - /opt/youtube-dl-front/database.json:/youtube-dl-front/server/database.json:rw
    labels:
      - "traefik.http.routers.ydf.rule=Host(`ydf.DOMAIN`)"
      - "traefik.http.routers.ydf.middlewares=test-auth@docker"
    networks:
      - public

```

then docker-compose up -d 

(note that root/ydf is my internal docker name for this hopefully Enriquito will follow up and push to docker hub :) )

Anyone have a better suggestion how to do this?  
(Or @Enriquito - if you can move config files to a separate folder under server/config ?  then we can map that folder in docker more easily).

Or better still - create the database.json at runtime if it doesn't exist, and put it in a config folder 

eg config/database.json

To be created at runtime if it doesn't exist.
Then we can just map the config folder, and your side will handle making the file.
